### ISSUE TITLE
Full month format in SDF equals to "MMMMM"

### ISSUE THREAD

**Issue by Scit** [elwin013/jdate-converter#3]
SimpleDateFormat uses 5 "M" letters for full month name representation:

yyyy.MMMMM.dd GGG hh:mm aaa	2009.June.30 AD 08:29 AM

https://docs.oracle.com/javase/tutorial/i18n/format/simpleDateFormat.html

**Comment by elwin013** [comment]
Hello @Scit!
Thank you for letting me know about that. Fixed in last commit :)

**Comment by Scit** [comment]
Hello! :) Thank you for your lib!

**Comment by elwin013** [comment]
@Scit new version (0.0.7) with fixes released :)
